### PR TITLE
Minor fixes and add  ReaderWriterQueue::max_capacity()

### PR DESCRIPTION
**Pull request by neomantra**
Per discussions in #22 

Also minor fixes for issues encountered on Linux.

Passes unit tests.  Benchmarks and stabtest still run fine.

### CODE REVIEW

**Comment by neomantra** [comment]
I went to unit test on OSX and saw that it wouldn't build.  So I applied some fixes to the makefiles and some missing headers.   It passes tests on OSX and Linux.

**Comment by cameron314** [comment]
Thanks for the pull request!

I've decided that it makes more sense not to expose the maximum capacity, since it's really just an implementation detail and requires a very specific scenario (i.e. empty queue) to be able to use the full maximum capacity. Instead, I'll implement the minimum capacity, and just call it `capacity()`.

I'm merging your PR anyway because of all the other fixes, though -- thanks! -- then I'll change the capacity.

**Comment by neomantra** [comment]
Great, thanks.  Sorry I didn't do a different branch for those build-oriented changesets.

**Comment by cameron314** [comment]
No worries, I'm not particularly fussy about workflow.

**Comment by cameron314** [comment]
Oops, I forgot about this pull request.

I take back what I said about implementing min capacity instead -- neither are perfectly accurate, so max capacity is just as useful, and it's already correctly implemented. I'm rebasing the patch and accepting it as is.

Thanks for your patience!

**Pull request merged**
