### PR TITLE
conan.io support

### PR DESCRIPTION
**Pull request by Manu343726**
Hi,

I've been porting all the third party dependencies of my [siplasplas](https://github.com/Manu343726/siplapslas) project to use the [conan.io C++ package manager](https://conan.io/). Since I already wrote [a package for readerwriterqueue](https://conan.io/source/readerwriterqueue/1.0.0/Manu343726/testing), I wanted to know if you could be interested in maintaining the package officially.

This PR contains:

 - `conanfile.py`: Conan recipe. It's a python script that describes how the package sources are downloaded, built, and then how the build artifacts are packaged.
 - `test_package`: An example consumer project to test the package is working correctly. (See [conan docs](http://docs.conan.io/en/latest/packaging/testing.html)).
 - `.travis.yml`: A [Travis CI](https://travis-ci.org/) CI build to test the package. It also can be used to automatically upload new package versions on releases.
 - Travis build and conan package badges for the README.

### CODE REVIEW

**Comment by cameron314** [comment]
Interesting. Hmm. I have even less free time than I used to, and have trouble keeping up with bug reports. But, conan.io seems cool and relatively low maintenance. I think I'll accept this PR and maintain the package, provided I can host it under my own handle (cameron314 or moodycamel). Give me a little time, though.

Could you fix the license to be 'Simplified BSD with part of blocking implementation under ZLIB'? This is not an MIT project ;-)

**Comment by Manu343726** [comment]
> Give me a little time, though.

Don't worry ;)

> Could you fix the license to be 'Simplified BSD with part of blocking implementation under ZLIB'? This is not an MIT project ;-)

Sure, I must have copy-pasted from another recipe or something

**Comment by cameron314** [comment]
Thanks! Your patience and contribution are really appreciated :-)

**Comment by Manu343726** [comment]
You're welcome. Ping me back for any question or help you need ;)

**Comment by IceflowRE** [comment]
Some news here?

**Comment by cameron314** [comment]
Sorry, been neglecting this. One conan package coming up!

**Comment by cameron314** [comment]
Hmm. The more I play around with Conan, the less I like it. It seems... needlessly complex.
I think if I create a Conan package, I won't be inclined to keep it up to date, which sort of defeats the purpose. So, I'm going to close this as 'Won't do', but if anyone else feels like maintaining a Conan package containing the headers from this repository, please feel free.

**Pull request closed without merging**
